# This is an example data set to showcase the expected structure.

# BASE INFORMATION
# This block contains basic information about bandpowers
band_power_file: "bandpowers/bbandpowers.txt" # Band power file name
covariance_file: "bandpowers/cov.bin" # Band power covariance file name
window_functions_file: "bandpowers/windowfunc.bin" # Window folder
effective_frequencies: "bandpowers/effective_frequencies.yaml" # Effective frequencies yaml file

# Template
# This block contains information about the template used in the likelihood
tsz_template: 'templates/dl_shaw_tsz_s10_153ghz_norm1_fake25000.txt'
ksz_template: 'templates/dl_ksz_oz_patchy_nolowell_20110708_norm1_fake25000.txt'
cib_1h : 'templates/dl_cib_1halo_norm1_25000.txt'
cib_2h : 'templates/dl_cib_2halo_norm1_25000.txt'
