# This is an example data set to showcase the expected structure.

# BASE INFORMATION
# This block contains basic information about bandpowers
band_power_file: "bandpowers/bbandpowers.txt" # Band power file name
covariance_file: "bandpowers/cov.bin" # Band power covariance file name
window_functions_file: "bandpowers/windowfunc.bin" # Window folder
effective_frequencies: "bandpowers/effective_frequencies.yaml" # Effective frequencies yaml file

# Template
# This block contains information about the template used in the likelihood
tsz_template: 'templates/dl_shaw_tsz_s10_153ghz_norm1_fake25000.txt'


#
# DATA SELECTION
# This list specifies the order of spectra along with the number of bins. This block gets used to extract a plethora of
# information about the data set (order, spec typres, frequencies, indices of spectra in a concatenated vector, ...),
# hence describing the data set accurately here is important.
spectra_info:
  - TT 95x95: 24
  - TT 95x150: 24
  - TT 95x220: 24
  - TT 150x150: 24
  - TT 150x220: 24
  - TT 220x220: 24


# DATA MODEL
# This list specifies the transformations, in order, to the theory spectra. Each entry is a block must contain which
# class ("Module") to use. The values here must match a python file and classes therein within the "transformations"
# folder.The other entries for a given transformation are then arguments needed to instantiate the class that cannot
# be supplied from likelihood attributes. See transformations/SPT3G_JAX_transformations_abstract_base.py for further
# details and transformations/SPT3G_JAX_transformations_common.py for examples.
data_model:
  - Module: "SPT3G_JAX_hiell_foregrounds.ForegroundComponents"
    foreground_tsz:
        type: "template"
        ell_norm: 3000
        filename: "dl_tsz_norm1.txt"
        param_names: ["D3000_143ghz_tsz"]
        sed: "sed_tsz"
    foreground_ksz:
        type: "template"
        ell_norm: 3000
        filename: "dl_ksz_norm1.txt"
        param_names: ["D3000_ksz"]
        sed: "sed_cmb"
    foreground_cib_pois:
        type: "poisson"
        ell_norm: 3000
        param_names: ["D3000_150ghz_cib_poisson"]
        sed: "sed_cib_poisson"
    foreground_cib_clus:
        type: "template"
        ell_norm: 3000
        filename: "dl_cluster_cib_norm1.txt"
        param_names: ["D3000_150ghz_cib_cluster"]
        sed: "sed_cib_cluster"
    foreground_rg:
        type: "poisson"
        ell_norm: 3000
        param_names: ["D3000_150ghz_rg_poisson"]
        sed: "sed_rg_poisson"  
    foreground_tsz_cib:
        type: "cross_correlation"
        list1: ["tsz"]
        list2: ["cib_poisson", "cib_cluster"]
        param_names: ["tsz_cib"]
        filename: None
    sed_cmb:
        type: "cmb"
        effective_freq_tag: 150
    sed_tsz:
        type: "tsz"
        effective_freq_tag: 143
    sed_cib_poisson:
        effective_freq_tag: 150
        type: "modbb"
        param_names: ["T_cib_pois", "beta_cib_pois", "sigmasq_cib_pois"]
    sed_cib_cluster:
        type: "modbb"
        param_names: ["T_cib_clus", "beta_cib_clus", "sigmasq_cib_clus"]
        effective_freq_tag: 150
    sed_rg_poisson:
        type: "powerlaw"
        param_names: [ "alpha_rg", "sigmasq_rg"]
        effective_freq_tag: 150





# GAUSSIAN PRIORS
# The list of Gaussian priors to be applied. Parameter name(s) and central_value (float or list of floats) are required,
# as well as either a prior_std (float value) or a prior_covariance (array of float values or relative path to text
# file) containing the covariance in the order specified in par_names.
#priors:
# - par_names: "tau"
#   central_value: 0.054
#   prior_std: 0.0074
# - par_names: ["Tcal90", "Tcal150", "Tcal220", "Ecal90", "Ecal150", "Ecal220"]
#    central_value: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
#    prior_covariance: "cal_covariance.dat"
